[package]
name = "fighter_renderer"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#brawllib_rs = "0.21"
brawllib_rs = { git = "https://github.com/rukai/brawllib_rs", rev = "e62bbcc20816e93580893049908c6ed231289a78" }
#brawllib_rs = { path = "/home/rukai2/Projects/Crates/brawllib_rs/brawllib_rs" }
wgpu = { version = "0.11", features = ["webgl"] }
serde_json = "1"
log = "0.4"

# wasm
console_log = "0.2"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3.55"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'CanvasRenderingContext2d',
  'DomTokenList',
  'Headers',
  'HtmlCanvasElement',
  'HtmlCollection',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
]

[profile.release]
lto = true
opt-level = 'z'
