[package]
name = "fighter_renderer"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#brawllib_rs = "0.21"
brawllib_rs = { git = "https://github.com/rukai/brawllib_rs", rev = "7c49d4e8feb306bc2e1ecdec32807598c1b1768f" }
#brawllib_rs = { path = "/home/rukai2/Projects/Crates/brawllib_rs/brawllib_rs" }
wgpu = { version = "0.11", features = ["webgl"] }
bincode = "1"

# wasm
console_log = "0.2"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
