---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  publish-binary:
    name: "Publish Binary to GitHub"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build & test
        run: |
          cargo test --release
          cargo build --release

          mkdir rukaidata
          cp target/release/rukaidata_bot rukaidata
          cp target/release/rukaidata_website rukaidata
          tar -cvzf rukaidata.tar.gz rukaidata
      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            *.tar.gz
